// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5j5hLV18wXxFP6MluCm0JyrEoMFKWtUU',
    appId: '1:770994369246:web:5a73cfc4493c9e19ae484f',
    messagingSenderId: '770994369246',
    projectId: 'flutter-uber-clone-ef3b1',
    authDomain: 'flutter-uber-clone-ef3b1.firebaseapp.com',
    databaseURL: 'https://flutter-uber-clone-ef3b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-uber-clone-ef3b1.appspot.com',
    measurementId: 'G-QPLET3C2PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEdbCKIViRo3YC5ltAW_1jFunWeW0PaE',
    appId: '1:770994369246:android:d238eeb0dce084f0ae484f',
    messagingSenderId: '770994369246',
    projectId: 'flutter-uber-clone-ef3b1',
    databaseURL: 'https://flutter-uber-clone-ef3b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-uber-clone-ef3b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsTddaE6ayvAs-V3pYNgByaji1P4IhGU4',
    appId: '1:770994369246:ios:66b613b9b4f3192fae484f',
    messagingSenderId: '770994369246',
    projectId: 'flutter-uber-clone-ef3b1',
    databaseURL: 'https://flutter-uber-clone-ef3b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-uber-clone-ef3b1.appspot.com',
    iosClientId: '770994369246-gjj4d5sclkkcg7skl2ctqh80cvilc718.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsTddaE6ayvAs-V3pYNgByaji1P4IhGU4',
    appId: '1:770994369246:ios:66b613b9b4f3192fae484f',
    messagingSenderId: '770994369246',
    projectId: 'flutter-uber-clone-ef3b1',
    databaseURL: 'https://flutter-uber-clone-ef3b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-uber-clone-ef3b1.appspot.com',
    iosClientId: '770994369246-gjj4d5sclkkcg7skl2ctqh80cvilc718.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberClone',
  );
}
